### ISSUE TITLE
FYI: The JSON Schema repo has a manifest.json schema to further help plugin devs

### ISSUE THREAD

**Issue by michaelabon** [elgatosf/schemas#1]
Hey, this repo looks really neat, and I'm excited to get to use the `validate` command to help check my plugins' manifests. I've been so looking forward to manifest validation like this that [I have previously submitted a manifest.json definition to the SchemaStore repository],(https://github.com/SchemaStore/schemastore/pull/3562) complete with tests against publicly available plugin manifests.

That JSON Schema file is really useful when added to a manifest.json file directly, [like in one of my plugins](https://github.com/michaelabon/streamdeck-inboxes/blob/03093c100bd791e644436db54dee9c28ede1f523/ca.michaelabon.streamdeck-inboxes.sdPlugin/manifest.json#L2). That way, you end up with great IDE support:

![Screenshot 2024-02-16 000114](https://github.com/elgatosf/schemas/assets/567950/a4d07558-632e-4318-9091-2391ddf4e171)

(I'm not opening this as an issue for you to fix anything. I just thought you should know that it's a feature out there in the world that makes it easier for people to develop Stream Deck plugins. If you want to update the SchemaStore definition when you make changes to the manifest definition, even better. Feel free to close this after reading it.)

**Comment by GeekyEggo** [comment]
Hi @michaelabon, great feedback, thank you. And thank you for helping to share the schemas on SchemaStore. Their repo is on our radar and is something we’re considering. In the interim, it’s at currently possible to reference the schemas online here:
- [Manifest schema](https://cdn.jsdelivr.net/npm/@elgato/schemas@latest/streamdeck/plugins/manifest.json)
- [Layout schema](https://cdn.jsdelivr.net/npm/@elgato/schemas@latest/streamdeck/plugins/layout.json)

I also notice you’re using VSCode and wanted to share a little feature I myself recently discovered; it’s possible to set the [`json.schemas`](https://code.visualstudio.com/docs/languages/json#_mapping-in-the-user-settings) setting so that specific files are automatically paired with schemas. This is handy as it allows you to remove the `$schema` property whilst retaining intellisense etc.

**Comment by michaelabon** [comment]
That's great to hear, thanks @GeekyEggo. If y'all are planning on using those jsdelivr links as your primary sources of truth, I know that you can configure SchemaStore to instead reference those URLs, rather than bothering to update both.

Regardless, again, this will help so much during plugin development to help improve the feedback loop when trying to deploy my own plugin for local development (much less packaging and distributing).

**Comment by GeekyEggo** [comment]
Hi @michaelabon, the schemas are now publicly accessible under the Elgato domain.
- https://schemas.elgato.com/streamdeck/plugins/manifest.json
- https://schemas.elgato.com/streamdeck/plugins/layout.json
